image: weboaks/node-karma-protractor-chrome

# # Stages definition
stages:
  - lint
  - test
  - build

# Lint phase
mc-francetransfert-upload-download-gui:lint:
  before_script:
    - echo "Pipeline Lint stage ..."
    - npm install
  stage: lint
  only:
    - develop
    - master
    - automation
  script:
    - npm run lint

# Test phase
mc-francetransfert-upload-download-gui:test:
  before_script:
    - echo "Pipeline Test stage ..."
    - npm install
  stage: test
  only:
    - develop
    - master
    - automation
  script:
    - npm run test

# Build phase
mc-francetransfert-upload-download-gui:build:
  before_script:
    - echo "Pipeline Build stage ..."
    - npm install
  stage: build
  only:
    - develop
    - master
    - automation
  script:
    - npm run build
