image: node:10

# # Stages definition
stages:
  - lint
  - test
  - build
  - docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/node_modules/
    - $CI_PROJECT_DIR/dist/

# Lint phase
mc-francetransfert-upload-download-gui:lint:
  before_script:
    - echo "Pipeline Lint stage ..."
    - npm install
  stage: lint
  script:
    - npm run lint

#Test phase
mc-francetransfert-upload-download-gui:test:
  image: weboaks/node-karma-protractor-chrome
  before_script:
    - echo "Pipeline Test stage ..."
  stage: test
  script:
    - npm run test

#Build phase
mc-francetransfert-upload-download-gui:build:
  before_script:
    - echo "Pipeline Build stage ..."
    - git clone -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.boost.open.global/mc/francetransfert/francetransfert-admin-gui.git
  stage: build
  script:
    - npm run build
    - cd francetransfert-admin-gui
    - npm install
    - npm run build
    - cp -R ./dist/* ../dist

#Docker phase
mc-francetransfert-upload-download-gui:docker:
  image: docker:stable
  before_script:
    - echo "Pipeline Docker stage ..."
  stage: docker
  only:
    - develop
    - master
  services:
    - docker:18-dind
  script:
    - _tmpTag="$(date "+%Y%m%d%H%M")"_"$CI_COMMIT_SHORT_SHA"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE":"$_tmpTag" .
    - docker tag "$CI_REGISTRY_IMAGE":"$_tmpTag" "$CI_REGISTRY_IMAGE":latest
    - docker push "$CI_REGISTRY_IMAGE":"$_tmpTag"
    - docker push "$CI_REGISTRY_IMAGE":latest
