export const CIRCLE_CONFIG = {
  backgroundPadding: 0,
  radius: 107,
  space: -9,
  outerStrokeWidth: 15,
  outerStrokeColor: '#0a0a0a',
  outerStrokeGradientStopColor: '#cacaca',
  innerStrokeColor: '#bcc2cb',
  innerStrokeWidth: 5,
  title: 'UI',
  imageHeight: 135,
  animateTitle: false,
  animationDuration: 1000,
  showTitle: false,
  showSubtitle: false,
  showUnits: false,
  showBackground: false,
  startFromZero: false,
  responsive: true
};
