export const CIRCLE_CONFIG = {
  backgroundOpacity: 1,
  backgroundStrokeWidth: 0,
  backgroundPadding: -34,
  radius: 20,
  space: -3,
  toFixed: 0,
  maxPercent: 100,
  outerStrokeWidth: 3,
  outerStrokeColor: "#0269cc",
  outerStrokeGradientStopColor: "#53a9ff",
  innerStrokeColor: "#dcdee0",
  innerStrokeWidth: 2,
  title: "UI",
  imageHeight: 30,
  imageWidth: 30,
  animateTitle: false,
  animationDuration: 1000,
  showTitle: false,
  showSubtitle: false,
  showUnits: false,
  showBackground: false,
  startFromZero: false
};
